services:
    locality_inference:
        image: locality_inference:latest
        container_name: locality_inference
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "${PORT}:${PORT}"
        profiles:
            - inference_services
        env_file:
            - .env
        networks:
            - locality_network
        deploy:
            resources:
                limits:
                    cpus: "1.0"
                    memory: "1G"
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"

    locality_redis:
        image: redis:latest
        container_name: locality_redis
        ports:
            - "6379:6379"
        profiles:
            - locality_assets
        networks:
            - locality_network
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: "200M"
        healthcheck:
            test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5
        volumes:
            - redis_data:/data/db
            - ./redis-entrypoint.sh:/usr/local/bin/redis-entrypoint.sh
        env_file:
            - .env
        command: ["bash", "/usr/local/bin/redis-entrypoint.sh"]

networks:
    locality_network:
        external: true

volumes:
    redis_data:
